# Generated by Django 4.0.4 on 2022-08-09 19:28

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=55, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=55, verbose_name='Второе имя')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('photo', models.ImageField(blank=True, default='author-photos/default.png', upload_to='auhtor-photos/%Y/%m/%d', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Illustrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=55, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=55, verbose_name='Второе имя')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Художник',
                'verbose_name_plural': 'Художники',
            },
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=55, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=55, verbose_name='Второе имя')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Переводчик',
                'verbose_name_plural': 'Переводчики',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='books.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Цена')),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='Скидка в процентах')),
                ('ISBN', models.CharField(max_length=255, verbose_name='ISBN')),
                ('page_count', models.PositiveIntegerField(verbose_name='Кол-во страниц')),
                ('weight', models.PositiveIntegerField(blank=True, verbose_name='Масса')),
                ('size', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, size=3, verbose_name='Размеры')),
                ('annotation', models.TextField(blank=True, verbose_name='Аннотация')),
                ('image', models.ImageField(blank=True, default='book-photos/default.png', upload_to='book-photos/%Y/%m/%d', verbose_name='Изображение')),
                ('in_storage', models.BooleanField(default=True, verbose_name='В наличии')),
                ('author', models.ManyToManyField(blank=True, to='books.author', verbose_name='Автор')),
                ('category', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.category', verbose_name='Категория')),
                ('illustrator', models.ManyToManyField(blank=True, to='books.illustrator', verbose_name='Художник')),
                ('publishing_house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.publishinghouse', verbose_name='Издательство')),
                ('translator', models.ManyToManyField(blank=True, to='books.translator', verbose_name='Переводчик')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
