# Generated by Django 4.0.4 on 2022-08-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_publishing_house_series_book_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
